# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

light_blue = Color.create({ name: 'Light Blue', hexcode: '#AAE0F7'})
orange = Color.create({ name: 'Orange', hexcode: '#FB971D'})
yellow = Color.create({ name: 'Yellow', hexcode: '#FFFF00'})
blue = Color.create({ name: 'Blue', hexcode: '#1245A8'})
fuschia = Color.create({ name: 'Fuschia', hexcode: '#FF00FF'})
brown = Color.create({ name: 'Brown', hexcode: '#945336'})
red = Color.create({ name: 'Red', hexcode: '#ED1B23'})
green = Color.create({ name: 'Green', hexcode: '#008000'})

title = TileGroup.create({ name: 'Title', description: '', color: light_blue })
metadata = TileGroup.create({ name: 'Metadata', description: '', color: orange })
author = TileGroup.create({ name: 'Author', description: '', color: yellow })
translation = TileGroup.create({ name: 'Books in Translation', description: '', color: blue })
new_release = TileGroup.create({ name: 'New Releases', description: '', color: fuschia })
non_fiction = TileGroup.create({ name: 'Non Fiction', description: '', color: brown })
diff_format = TileGroup.create({ name: 'Different Formats', description: '', color: red })
genre = TileGroup.create({ name: 'Genre', description: '', color: green })

number = Tile.create({ name: 'Number in Title', description: 'Read a book with a number in the title', tile_group: title })
day_time = Tile.create({ name: 'Day or Time in Title', description: 'Read a book with a day or time in the title', tile_group: title })
award = Tile.create({ name: 'Award Winning', description: 'Read a book that has won an award', tile_group: metadata })
before_1950 = Tile.create({ name: 'Released Before 1950', description: 'Read a book that was released before 1950', tile_group: metadata })
debut = Tile.create({ name: 'Debut Author', description: 'Read a book by a debut author', tile_group: author })
under_30 = Tile.create({ name: 'Author Under 30', description: 'Read a book by an author under 30', tile_group: author })
asia = Tile.create({ name: 'Language Spoken in Asia', description: 'Read a book that has been translated into English from a language spoken in Asia', tile_group: translation })
europe = Tile.create({ name: 'Language Spoken in Asia', description: 'Read a book that has been translated into English from a language spoken in Europe', tile_group: translation })
this_year = Tile.create({ name: 'Released This Year', description: 'Read a book that was released this year', tile_group: new_release })
this_decade = Tile.create({ name: 'Released This Decade', description: 'Read a book that was released this decade', tile_group: new_release })
memoir = Tile.create({ name: 'Memoir', description: 'Read a memoir', tile_group: non_fiction })
political = Tile.create({ name: 'Political', description: 'Read a political book', tile_group: non_fiction })
audiobook = Tile.create({ name: 'Audiobook', description: 'Listen to an audiobook', tile_group: diff_format })
graphic_novel = Tile.create({ name: 'Graphic Novel', description: 'Read a graphic novel', tile_group: diff_format })
sci_fi = Tile.create({ name: 'Sci-Fi', description: 'Read a sci-fi book', tile_group: genre })
fantasy = Tile.create({ name: 'Fantasy', description: 'Read a fantasy book', tile_group: genre })

murakami = Recommendation.create({ tile: number, book: Book.create({ name: '1Q84', author: 'Haruki Murakami', cover_image: '', genre: '', isbn: '' }) })
mandel = Recommendation.create({ tile: number, book: Book.create({ name: 'Station 11', author: 'Emily St John Mandel', cover_image: '', genre: '', isbn: '' }) })
martel = Recommendation.create({ tile: number, book: Book.create({ name: 'Life of Pi', author: 'Yann Martel', cover_image: '', genre: '', isbn: '' }) })
han = Recommendation.create({ tile: day_time, book: Book.create({ name: 'The Summer I Turned Pretty', author: 'Jenny Han', cover_image: '', genre: '', isbn: '' }) })
paralkar = Recommendation.create({ tile: day_time, book: Book.create({ name: 'Night Theatre', author: 'Vikram Paralkar', cover_image: '', genre: '', isbn: '' }) })
welch = Recommendation.create({ tile: day_time, book: Book.create({ name: 'Winter in the Blood', author: 'James Welch', cover_image: '', genre: '', isbn: '' }) })
thammavongsa = Recommendation.create({ tile: award, book: Book.create({ name: 'How To Pronounce Knife', author: 'Souvankham Thammavongsa', cover_image: '', genre: '', isbn: '' }) })
james = Recommendation.create({ tile: award, book: Book.create({ name: 'The Brief History Of Seven Killings', author: 'Marlon James', cover_image: '', genre: '', isbn: '' }) })
walker = Recommendation.create({ tile: award, book: Book.create({ name: 'The Color Purple', author: 'Alice Walker', cover_image: '', genre: '', isbn: '' }) })
hurston = Recommendation.create({ tile: before_1950, book: Book.create({ name: 'Their Eyes Were Watching God', author: 'Nora Zeale Hurston', cover_image: '', genre: '', isbn: '' }) })
soseki = Recommendation.create({ tile: before_1950, book: Book.create({ name: 'I Am A Cat', author: 'Natsume Soseki', cover_image: '', genre: '', isbn: '' }) })
paz = Recommendation.create({ tile: before_1950, book: Book.create({ name: 'The Labyrinth of Solitude', author: 'Octavio Paz', cover_image: '', genre: '', isbn: '' }) })
orange = Recommendation.create({ tile: debut, book: Book.create({ name: 'There There', author: 'Tommy Orange', cover_image: '', genre: '', isbn: '' }) })
taylor = Recommendation.create({ tile: debut, book: Book.create({ name: 'Real Life', author: 'Brandon Taylor', cover_image: '', genre: '', isbn: '' }) })
awad = Recommendation.create({ tile: debut, book: Book.create({ name: 'Bunny', author: 'Mona Awad', cover_image: '', genre: '', isbn: '' }) })
vuong = Recommendation.create({ tile: under_30, book: Book.create({ name: 'The Night Sky with Exit Wounds', author: 'Ocean Vuong', cover_image: '', genre: '', isbn: '' }) })
smith = Recommendation.create({ tile: under_30, book: Book.create({ name: 'White Teeth', author: 'Zadie Smith', cover_image: '', genre: '', isbn: '' }) })
brosch = Recommendation.create({ tile: under_30, book: Book.create({ name: 'Hyperbole And A Half', author: 'Alie Brosch', cover_image: '', genre: '', isbn: '' }) })
ogawa = Recommendation.create({ tile: asia, book: Book.create({ name: 'The Memory Police', author: 'Yoko Ogawa', cover_image: '', genre: '', isbn: '' }) })
miaojin = Recommendation.create({ tile: asia, book: Book.create({ name: 'Notes of a Crocodile', author: 'Qiu Miaojin', cover_image: '', genre: '', isbn: '' }) })
mishima = Recommendation.create({ tile: asia, book: Book.create({ name: 'Confessions of a Mask', author: 'Yukio Mishima', cover_image: '', genre: '', isbn: '' }) })
marquez = Recommendation.create({ tile: europe, book: Book.create({ name: '100 Years of Solitude', author: 'Gabriel Garcia Marquez', cover_image: '', genre: '', isbn: '' }) })
cardoso = Recommendation.create({ tile: europe, book: Book.create({ name: 'Chronicle of the Murdered House', author: 'Luico Cardoso', cover_image: '', genre: '', isbn: '' }) })
duras = Recommendation.create({ tile: europe, book: Book.create({ name: 'Blue Eyes, Black Hair', author: 'Marguerite Duras', cover_image: '', genre: '', isbn: '' }) })
jemisin = Recommendation.create({ tile: this_year, book: Book.create({ name: 'The City We Became', author: 'N.K. Jemisin', cover_image: '', genre: '', isbn: '' }) })
king = Recommendation.create({ tile: this_year, book: Book.create({ name: 'Indians on Vacation', author: 'Thomas King', cover_image: '', genre: '', isbn: '' }) })
staples = Recommendation.create({ tile: this_year, book: Book.create({ name: 'This Town Sleeps', author: 'Dennis E Staples', cover_image: '', genre: '', isbn: '' }) })
mcbride = Recommendation.create({ tile: this_decade, book: Book.create({ name: 'Deacon King Kong', author: 'James McBride', cover_image: '', genre: '', isbn: '' }) })
offill = Recommendation.create({ tile: this_decade, book: Book.create({ name: 'Weather', author: 'Jenny Offill', cover_image: '', genre: '', isbn: '' }) })
clarke = Recommendation.create({ tile: this_decade, book: Book.create({ name: 'Piranesi', author: 'Susanna Clarke', cover_image: '', genre: '', isbn: '' }) })
murakami2 = Recommendation.create({ tile: memoir, book: Book.create({ name: 'What I Talk About When I Talk About Running', author: 'Haruki Murakami', cover_image: '', genre: '', isbn: '' }) })
nixon = Recommendation.create({ tile: memoir, book: Book.create({ name: 'Nitisanak', author: 'Lindsay Nixon', cover_image: '', genre: '', isbn: '' }) })
noah = Recommendation.create({ tile: memoir, book: Book.create({ name: 'Born A Crime', author: 'Trevor Noah', cover_image: '', genre: '', isbn: '' }) })
banerjee = Recommendation.create({ tile: political, book: Book.create({ name: 'Good Economics for Hard Times', author: 'Abhijit V. Banerjee', cover_image: '', genre: '', isbn: '' }) })
obama_m = Recommendation.create({ tile: political, book: Book.create({ name: 'Becoming', author: 'Michelle Obama', cover_image: '', genre: '', isbn: '' }) })
obama_b = Recommendation.create({ tile: political, book: Book.create({ name: 'A Promised Land', author: 'Barack Obama', cover_image: '', genre: '', isbn: '' }) })
gaiman = Recommendation.create({ tile: audiobook, book: Book.create({ name: 'The Graveyard Book', author: 'Neil Gaiman', cover_image: '', genre: '', isbn: '' }) })
saunders = Recommendation.create({ tile: audiobook, book: Book.create({ name: 'Lincoln In The Bardo', author: 'George Saunders', cover_image: '', genre: '', isbn: '' }) })
cole = Recommendation.create({ tile: audiobook, book: Book.create({ name: 'The Skin We’re In', author: 'Desmond Cole', cover_image: '', genre: '', isbn: '' }) })
speigelman = Recommendation.create({ tile: graphic_novel, book: Book.create({ name: 'Maus', author: 'Art Speigelman', cover_image: '', genre: '', isbn: '' }) })
takei = Recommendation.create({ tile: graphic_novel, book: Book.create({ name: 'They Called Us Enemy', author: 'George Takei', cover_image: '', genre: '', isbn: '' }) })
vaugn = Recommendation.create({ tile: graphic_novel, book: Book.create({ name: 'Paper Girls', author: 'Brian K Vaughn', cover_image: '', genre: '', isbn: '' }) })
cixin = Recommendation.create({ tile: sci_fi, book: Book.create({ name: 'The Three Body Problem', author: 'Liu Cixin', cover_image: '', genre: '', isbn: '' }) })
jemisin2 = Recommendation.create({ tile: sci_fi, book: Book.create({ name: 'The Fifth Season', author: 'N.K. Jemisin', cover_image: '', genre: '', isbn: '' }) })
weir = Recommendation.create({ tile: sci_fi, book: Book.create({ name: 'The Martian', author: 'Andy Weir', cover_image: '', genre: '', isbn: '' }) })
adeyemi = Recommendation.create({ tile: fantasy, book: Book.create({ name: 'Children Of Blood And Bone', author: 'Tomi Adeyemi', cover_image: '', genre: '', isbn: '' }) })
nicholson = Recommendation.create({ tile: fantasy, book: Book.create({ name: 'Love Beyond Body Space and Time', author: 'Hope Nicholson', cover_image: '', genre: '', isbn: '' }) })
moreon_garcia = Recommendation.create({ tile: fantasy, book: Book.create({ name: 'Gods of Jade and Shadow', author: 'Silvia Moreno-Garcia', cover_image: '', genre: '', isbn: '' }) })

